### ISSUE TITLE
mapquest support discontinued

### ISSUE THREAD

**Issue by aahunter** [muccg/docker-bpa-ckan#3]
https://github.com/ckan/ckanext-geoview/issues/46

**Comment by sthysel** [comment]
ckanext.spatial.common_map.type = custom
ckanext.spatial.common_map.custom.url = http://tile.openstreetmap.org/{z}/{x}/{y}.png 
ckanext.spatial.common_map.attribution = Map tiles & Data by OpenStreetMap, under CC BY SA.

Added the magic

**Comment by grahame** [comment]
Pushed live.
